### ISSUE TITLE
Unable to specify more than one repo in Opentelemetry.Ecto.setup/2

### ISSUE THREAD

**Issue by smashedtoatoms** [open-telemetry/opentelemetry-erlang-contrib#110]
**Describe the bug**
I have multiple repos but the only setup command that seems to work for opentelemetry_ecto is `:repo`

**Expected behavior**
I expect to run `OpentelemetryEcto.setup([:reel, :repo])` as well as `OpentelemetryEcto.setup([:reel, MyApp.Repo])` and `OpentelemetryEcto.setup([:reel, MyApp.Repo2])` and have them all work 

**Additional context**
It is entirely possible that I don't understand how this is supposed to work, so forgive me if that is the case.  How do I specify more than one Repo if more than one repo exists?

**Comment by bryannaegele** [comment]
The telemetry event name in your config should be set the same for both. The name of the repo is taken from event automatically

**Comment by smashedtoatoms** [comment]
In that case, I should only need a single config and I should see all of my ecto telemetry data?  If that is the case, do you have any ideas why I'm only seeing it for one repo, the one called Repo?

**Comment by bryannaegele** [comment]
Correct. Have you confirmed that you have set the telemetry name the same for both in your app config?

**Comment by smashedtoatoms** [comment]
I'm definitely missing something conceptually. How do I set the telemetry
name in the app config? As far as I can tell, I can set it to :repo, and
that's it.

**Comment by bryannaegele** [comment]
See `telemetry_prefix` https://hexdocs.pm/ecto/Ecto.Repo.html

**Comment by smashedtoatoms** [comment]
Hey @bryannaegele, I have to apologize.  I haven't gotten to work in elixir/erlang for over five years and I honestly forgot what it was like to use software written by people who can actually think and design things properly.  The solution is so elegant and well thought-out that I didn't even think to look for it because nothing in the last five years of my life has worked this well.

My problem was that all of my repos had a different `telemetry_prefix`, as you suspected.  The default is based on the module name, as you know.  Once I set the `telemetry_prefix` to the same value for all of the repos, it worked exactly as expected/designed.  Sorry to have wasted your time.  This library is so smooth it slipped out of my hands.  Thanks so much.
