### ISSUE TITLE
Any chance for an opentelemetry_tesla publish

### ISSUE THREAD

**Issue by dhaspden** [open-telemetry/opentelemetry-erlang-contrib#124]
We'd like to be able to update all of our OpenTelemetry packages to their newest version but because of the pinned versions of this package we're currently unable to. Is there any way that an updated version of `opentelemetry_tesla` can be published, even if all that's in there is the relaxed version requirements?

**Comment by tsloughter** [comment]
We'll get one out as soon as https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/118 is merged. Should be today.

**Comment by dhaspden** [comment]
Cheers!

**Comment by bryannaegele** [comment]
Done

**Comment by dhaspden** [comment]
Thanks for the push on this, I really appreciate it. 🙏
