### ISSUE TITLE
Provide an API for registering spans instead of telemetry_registry

### ISSUE THREAD

**Issue by josevalim** [open-telemetry/opentelemetry-erlang-contrib#190]
Currently `opentelemetry_telemetry` relies on `telemetry_registry` but I am wondering if that's an anti-pattern because that takes control away from users. Instead, we should add a public API to register spans:

    :opentelemetry_telemetry.register(["foo.bar.baz", "bar.bar.bat"])

If you want to rely on `telemetry_registry`, then you could do:

    :opentelemetry_telemetry.register(:telemetry_registry.spannable_events())

And even that has advantages because now I can add or remove anything I'd like. So I think the user should be in control of what is being reported and what isn't. Thoughts?

**Comment by bryannaegele** [comment]
That bit of code is an undocumented experiment that was in there from a few years ago to play with auto-instrumentation from registered telemetry attributes in modules. I don't know that it has a future beyond that experiment as nobody has really asked for it and there's a requirement that folks use the registry which hasn't had much traction. If we deleted that undocumented feature, the dep would go away.

The public API is really just https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/utilities/opentelemetry_telemetry/src/otel_telemetry.erl#L9-L11 which is what the Elixir module exposes/documents.

**Comment by josevalim** [comment]
Ah, I see. Yeah, so maybe it makes sense to remove the code and the dep then, given that folks are using opentelemetry_phoenix and friends and we are pulling in basically unused code?

Thank you for the prompt reply :heart:

**Comment by bryannaegele** [comment]
Yeah, I agree.

**Comment by tsloughter** [comment]
:+1:

**Comment by bryannaegele** [comment]
Registry has been removed.
