### ISSUE TITLE
Only run Elixir formatter on latest version of Elixir

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang-contrib#199]
Currently it checks formatting on every version of Elixir we support, this will result in check failures between versions at times.

We should only run the format checking on the latest version.

**Comment by bryannaegele** [comment]
Pretty sure #188 will address this

**Comment by tomtaylor** [comment]
Yes #188 does this.

**Comment by tsloughter** [comment]
Ah, great!

**Comment by bryannaegele** [comment]
Fixed in #188
