### ISSUE TITLE
Ecto: preloads not linked to parent span

### ISSUE THREAD

**Issue by dvic** [open-telemetry/opentelemetry-erlang-contrib#25]
By default, Ecto executes preloads (if there are more than one) in parallel, e.g.,

```elixir
Repo.all(from(Demo.Post, preload: [:authors, :comments]))
```

or 

```elixir
Repo.all(Demo.Post)
|> Repo.preload([:authors, :comments])
```

This will result in the two queries for `authors` and `comments` not to be linked to the parent span.

**Solution**
It would be nice if the preload spans were a child of the parent span (the query for `Demo.Post` in the above example) or that they are created with a link to this parent span (similar to how it's done with Oban jobs in #6).

**Alternatives**
One workaround for this is passing in_parallel: false to Repo.all or Repo.preload, but this might impact the performance.

**Additional context**
Previously reported in https://github.com/opentelemetry-beam/opentelemetry_ecto/issues/15

**Comment by bryannaegele** [comment]
The generic approach has a couple of challenges in that:
* You may not want a span in that task, just continue the currently active span
* Linking is not supported in most tooling, so you'd end up with even less insight as that span won't even be affiliated with that trace in UIs.

I think the solution you proposed makes sense as something for this particular library. Tristan and I discussed this as a generic thing about a month ago and settled on creating a utility to make the searching generic. I think I have it started (pretty simple) but I didn't have time to finish. I'll see if I can get that up soon.
