### ISSUE TITLE
:opentelemetry_telemetry, "1.1.0" is missing dependency to :telemetry_registry, "~> 0.3.0"

### ISSUE THREAD

**Issue by ebengt** [open-telemetry/opentelemetry-erlang-contrib#275]
**Describe the bug**
Add a dependency in mix.exs that depends on `opentelemetry_telemetry, "~> 1.0"`, example: `opentelemetry_phoenix "~> 1.1"`
Do **mix test**. The error is:
`** (Mix) Could not start application telemetry_registry: could not find application file: telemetry_registry.app
`
This is because (I think) opentelemetry_telemetry, "1.1.0" in mix.lock does not depend on telemetry_registry

**Expected behavior**
Previously, opentelemetry_telemetry, "1.0.0", would depend on `telemetry_registry, "~> 0.3.0"`, and include telemetry_registry in the build.

**Additional context**
If I add opentelemetry_telemetry, "1.0.0" to mix.exs, telemetry_registry is included in the build.
Alternatively, I can add `telemetry_registry, "~> 0.3.0"` to mix.exs

**Comment by bryannaegele** [comment]
That dependency was removed in 1.1.0. I don't know why it would cause an issue in your application as it isn't in any of the files shipped with the library (`rebar.config`, `rebar.lock`, `mix.exs`) so you shouldn't have seen it as a dependency. There was a remnant in the `mix.lock` file but that isn't something shipped with the library. Nevertheless, I removed it from the lock file and published a new version.
