### ISSUE TITLE
Depending on opentelemetry_cowboy will stop mix test

### ISSUE THREAD

**Issue by ebengt** [open-telemetry/opentelemetry-erlang-contrib#282]
**Describe the bug**
Create new mix project. Add `{opentelemetry_cowboy, "~> 0.2"}` to deps. Do
```
$ mix test
** (Mix) Could not start application telemetry_registry: could not find application file: telemetry_registry.app

```
When I check opentelemetry_cowboy it has  
`opentelemetry_cowboy/src/opentelemetry_cowboy.app.src:6:                              telemetry_registry]},`
But no **telemetry_registry** in rebar.config for opentelemetry_cowboy

**Expected behavior**
No complaints about missing teletry_registry when running test.

**Additional context**
I mistakenly thought this was due to opentelemetry_telemetry, but this time I am right. Or I will be next time.

**Comment by bryannaegele** [comment]
I'm still unclear on what the issue is. `opentelemetry_cowboy` has no dependency on `telemetry_registry`. If you update `opentelemetry_telemetry` then there should be no dependency anywhere in your code.

Have you deleted your `deps` and `_build` directories? I feel like you have a bunch of deps that aren't getting recompiled.

**Comment by ebengt** [comment]
Yes, I delete mix.lock, deps/ and _build/, before doing **deps.get**
I think it is the line
` opentelemetry_cowboy/src/opentelemetry_cowboy.app.src:6:                              telemetry_registry]},`
that cause the problem. opentelemetry_cowboy wants application telemetry_registry, without including it in rebar.config deps.

**Comment by bryannaegele** [comment]
This was a package configuration issue accidentally including the lock file. A new version has been published.
