### ISSUE TITLE
OpentelemetryBandit is incompatible with Bandit v1.4.0

### ISSUE THREAD

**Issue by ibarchenkov** [open-telemetry/opentelemetry-erlang-contrib#308]
**Describe the bug**
In Bandit 1.4.0, `status`, `method` and `request_target` attributes [were removed](https://github.com/mtrudel/bandit/blob/main/CHANGELOG.md#changes-1) from telemetry metadata, which are utilised in [multiple places](https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/3f13bc8b2042071b723d0ea8c7b118fd10f42d26/instrumentation/opentelemetry_bandit/lib/opentelemetry_bandit.ex#L68) in OpentelemetryBandit.

**Expected behavior**
These attributes should be replaced with corresponding data from the `conn` struct.

**Additional context**
I'm willing to provide a PR if no one is working on this issue yet.

**Comment by VictorGaiva** [comment]
There is an [open PR](https://github.com/samokat-oss/opentelemetry-bandit/pull/1) for fixing this issue on the original repository for the package.
