### ISSUE TITLE
opentelemetry_dataloader package is not available in hex.pm

### ISSUE THREAD

**Issue by yordis** [open-telemetry/opentelemetry-erlang-contrib#333]
**Describe the bug**

Hey folks, I am not sure if it is intentionally or not, but, `opentelemetry_dataloader` package is not in hex.pm https://hex.pm/packages?search=opentelemetry_dataloader&sort=recent_downloads

**Expected behavior**

To be released

**Additional context**

**Comment by btkostner** [comment]
@bryannaegele Sorry for the personal ping, but any chance we can get this published?

**Comment by bryannaegele** [comment]
Done
