### ISSUE TITLE
cowboy integration always sets error on span with http.status set to 0

### ISSUE THREAD

**Issue by dvic** [open-telemetry/opentelemetry-erlang-contrib#36]
I debugged this and it turns out `resp_status` is not an integer but `"200 OK"` in my case (`cowboy` 2.9.0 and `cowboy_telemetry` 0.3.1), while the code (as far as I can see) assumes it's an integer?

According to https://github.com/ninenines/cowboy/blob/8795233c57f1f472781a22ffbf186ce38cc5b049/src/cowboy.erl#L37 the resp_status can indeed be a binary as well.

Furthermore, shouldnt' `http.status` be `http.status_code`?

**Comment by bryannaegele** [comment]
Resolved by #48
