### ISSUE TITLE
Phoenix instrumentation library is using an incorrect tracer

### ISSUE THREAD

**Issue by indrekj** [open-telemetry/opentelemetry-erlang-contrib#39]
**Describe the bug**

`opentelemetry_phoenix` does not include tags `otel.library.name` and `otel.library.version`.

I'm using latest opentelemetry libraries:
* opentelemetry & opentelemetry_api: latest commit in main branch [590d87f](https://github.com/open-telemetry/opentelemetry-erlang/commit/590d87f4cbc9085e4ad8cff0c1c97825f54b85d4)
* opentelemetry_phoenix: 1.0.0-rc.5

**Expected behavior**
Spans generated by opentelemetry_phoenix must include `otel.library.name` and `otel.library.version`.

**Additional context**
This problem was previously also present on ecto library but the commit on [opentelemetry_api](https://github.com/open-telemetry/opentelemetry-erlang/commit/f7bd7edaf129308e2bbb04a47a3dabe0c4f2c740) repository fixed that.

As far as I can tell, this is because the phoenix instrumentation library is using [opentelemetry_telemetry](https://github.com/opentelemetry-beam/opentelemetry_telemetry) which uses [get_tracer](https://github.com/opentelemetry-beam/opentelemetry_telemetry/blob/main/src/otel_telemetry.erl#L41) call, but the tracer isn't registered (properly).

I also did some debugging inside the start_telemetry_span function:
```
    erlang:display(opentelemetry:get_application_tracer(opentelemetry_phoenix))
    -- returns default tracer

    erlang:display(opentelemetry:get_application_tracer('Elixir.OpentelemetryPhoenix'))
    -- returns CORRECT tracer

    erlang:display(opentelemetry:get_tracer('opentelemetry_phoenix'))
    -- returns default tracer (current code)

    erlang:display(opentelemetry:get_tracer('Elixir.OpentelemetryPhoenix'))
    -- returns default tracer
```

I would fix this myself but I'm unsure what's the correct solution here.

**Comment by tsloughter** [comment]
Yup, thanks, I thought there was already a fix merged for this but I guess not, @bryannaegele ?

**Comment by tsloughter** [comment]
Oh right, nevermind, the fix is in the Elixir otel api, not particular to the phoenix integration.

So this is fixed in `main` of opentelemetry-erlang but has to be released so the integrations can update their deps and be published.

**Comment by indrekj** [comment]
> So this is fixed in main of opentelemetry-erlang but has to be released so the integrations can update their deps and be published.

I don't think so. I'm locally using the main branch with an override. That fixed the ecto instrumentation. But Phoenix is still broken. I think this is something different. Though maybe I'm wrong.

**Comment by tsloughter** [comment]
No, you are right, it was 2 issues, only 1 fixed in the api, the other is the name of the tracer the Phoenix lib uses is wrong.

**Comment by indrekj** [comment]
One solution that locally works:

In opentelemetry_telemetry:
```diff
diff --git a/src/otel_telemetry.erl b/src/otel_telemetry.erl
index 58762e6..ae7e564 100644
--- a/src/otel_telemetry.erl
+++ b/src/otel_telemetry.erl
@@ -38,7 +38,7 @@ trace_application(Application, _Opts) ->
 -spec start_telemetry_span(atom(), opentelemetry:span_name(), telemetry:event_metadata(), otel_span:start_opts()) -> opentelemetry:span_ctx().
 start_telemetry_span(TracerId, SpanName, EventMetadata, Opts) ->
     ParentCtx = otel_tracer:current_span_ctx(),
-    Tracer = opentelemetry:get_tracer(TracerId),
+    Tracer = opentelemetry:get_application_tracer(TracerId),
     Ctx = otel_tracer:start_span(Tracer, SpanName, Opts),
     otel_tracer:set_current_span(Ctx),
     _ = store_ctx({ParentCtx, Ctx}, TracerId, EventMetadata),
```

and in opentelemetry_phoenix:
```diff
diff --git a/instrumentation/opentelemetry_phoenix/lib/opentelemetry_phoenix.ex b/instrumentation/opentelemetry_phoenix/lib/opentelemetry_phoenix.ex
index 717fdbd..b83f9da 100644
--- a/instrumentation/opentelemetry_phoenix/lib/opentelemetry_phoenix.ex
+++ b/instrumentation/opentelemetry_phoenix/lib/opentelemetry_phoenix.ex
@@ -27,7 +27,7 @@ defmodule OpentelemetryPhoenix do
   alias OpenTelemetry.Span
   alias OpentelemetryPhoenix.Reason
 
-  @tracer_id :opentelemetry_phoenix
+  @tracer_id __MODULE__
 
   @typedoc "Setup options"
   @type opts :: [endpoint_prefix()]
```

but I don't know if this would be a good solution or not.

**Comment by indrekj** [comment]
This seems to be fine with the latest versions. Closing this.
