### ISSUE TITLE
opentelemetry_bandit add extract_client_address_fn option

### ISSUE THREAD

**Issue by danielspofford** [open-telemetry/opentelemetry-erlang-contrib#410]
**Is your feature request related to a problem? Please describe.**

There are scenarios where [`client.address`](https://opentelemetry.io/docs/specs/semconv/attributes-registry/client/) and [`network.peer.address`](https://opentelemetry.io/docs/specs/semconv/attributes-registry/network/) ought to be different, e.g., when a proxy is between the client and server. This is handled correctly when spec'd headers (like `forwarded`) are used to convey this information. However, when the [PROXY protocol](https://github.com/haproxy/haproxy/blob/master/doc/proxy-protocol.txt) is in use, no such headers are set. I am already reading and parsing the PROXY protocol and providing it to the application via adapter state (tucked into transport.socket.socket). However, I do not see a way to have traces report this information accurately: where the `client.address` is informed by the PROXY protocol, but the `network.peer.address` is informed by the peer's address.

The value resolution for `network.peer.address` is perfect: it ultimately calls peername on an underlying transport.

The value resolution for `client.address` is where the friction lays. It attempts to extract a value from headers, and if no value is found, it falls back to calling peername on the underlying transport. This results in both fields having the same value: the peer's address.

**Describe the solution you'd like**

Add extract_client_address_fn option so that I can provide my own logic to read the PROXY protocol data off the conn, e.g., `adapter_state.transport.socket.socket.proxy_protocol_data`.

**Describe alternatives you've considered**

I could just fork this repository and patch in this functionality, but I do not want to carry a patch forward indefinitely, and I think this sort of functionality will be relevant to anyone using the PROXY protocol as well as anyone who derives their client address by means outside of one-to-one header value extraction. For context, this is forced on you when using AWS Network Load Balancers as they act solely on the TCP layer and in turn provide client addresses via the PROXY protocol.

Out-of-scope of this repository:

@mtrudel I know you've discussed the PROXY protocol before in the context of Bandit and Thousand Island, and I've seen you chime in a few times in this repository, so I apologize for the ping, but please LMK if I am missing a more convenient way to achieve this or if there is a direction that is most aligned with some higher goal. With respect to your repositories, I have considered:

- If I change my transport's peername callback to return the data from the PROXY protocol, then both fields get impacted - this forces a decision between only getting the client address versus only getting the peer address. I require both.
- While I would be happy to, I cannot inject a `forwarded` header because the Bandit.Pipeline.run/4 call reads the headers from the socket, builds the conn, and emits the span - and there is no place for me to hook into or impact the result.
- Transports could support a dedicated function for this like `clientname` to mirror `sockname` and `peername`, but IMO that is too heavy-handed and precedent breaking with gen_tcp.

--

I know this is a bit of a cross-cutting issue so I apologize if it is better hosted elsewhere, just LMK.

**Comment by mtrudel** [comment]
IMO the right place for this is on Plug; the meaning of both local and remote addresses in there are generally underspecified and the source of much confusion in this regard. Sadly, as Plug exists today there's not a whole lot of room to change this without breaking a ton of existing behaviour in countless libraries; what inconsistencies exist are load bearing. 

OTOH, the underlying Transport is just that; a transport. I don't think it ought to interpret or even know about proxy headers or other protocol level concerns. 

Would a plug early in your pipeline be able to read headers as required and add :private attributes as needed?

**Comment by bryannaegele** [comment]
> Would a plug early in your pipeline be able to read headers as required and add :private attributes as needed?

One can always update an attribute at any time in the endpoint/plug stack, so this is a viable pattern. We're just setting things according to the spec in this library. The defaults can be overridden.

**Comment by danielspofford** [comment]
Hey folks, appreciate the responses 🙇 

> OTOH, the underlying Transport is just that; a transport. I don't think it ought to interpret or even know about proxy headers or other protocol level concerns.
>
> Would a plug early in your pipeline be able to read headers as required and add :private attributes as needed?

Apologies if I'm misunderstanding you but, just to be clear, the word "header" gets mentioned a lot when discussing the PROXY protocol, but I want to make explicit that this data is received as a raw binary preamble at the very start of a TCP connection (prior even to TLS handshake data for example, let alone subsequent HTTP data). They call it a "header", but it is not an **_HTTP_** header.

> Would a plug early in your pipeline be able to read headers as required and add :private attributes as needed?

I was under the impression something like this would not be relevant because the problem is not getting the data onto the conn eventually, it was having it on the conn early enough that what this library initially set the `client.address` to was actually impacted.

But given Bryan's response quoted below I may be able to change my approach!

> One can always update an attribute at any time in the endpoint/plug stack

I did not realize it was "legal" for me to simply overwrite attributes on this span (wasn't sure if they would get clobbered or it would break something that relied on it). This is very exciting as its the closest to success so far.

I tried this and it almost worked, with the exception that doing something like:

```
Tracer.set_attribute("client.address", value)
```

Results in duplicate tags being reported like:

<img width="301" alt="image" src="https://github.com/user-attachments/assets/0c29ddc6-cf63-4c47-9592-9049b9665430">

Is it possible to actually overwrite the value? Not stoked about having a tag key defined twice.

Thanks again for the conversation all.

**Comment by bryannaegele** [comment]
Glad it worked for ya! There's nothing really "illegal" about what this approach. This is a perfectly valid situation for the user to change the value.

> Results in duplicate tags being reported like:

Use the semantic conventions library for the keys. Essentially what you did was add an attribute with that name and a string key where they key is actually an atom. Stick to semconv for compatibility.

https://hexdocs.pm/opentelemetry_semantic_conventions/OpenTelemetry.SemConv.ClientAttributes.html#client_address/0
