### ISSUE TITLE
Inject trace headers in phoenix response

### ISSUE THREAD

**Issue by btkostner** [open-telemetry/opentelemetry-erlang-contrib#84]
**Is your feature request related to a problem? Please describe.**
The Phoenix instrumentation does not inject tracing headers in the response

**Describe the solution you'd like**
Similar to how [`:otel_propagator_text_map.extract`](https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/instrumentation/opentelemetry_phoenix/lib/opentelemetry_phoenix.ex#L102) already extracts tracing headers, there should be an `otel_propagator_text_map.inject` to add tracing headers to the response.

**Describe alternatives you've considered**
This _can_ be done in the application side with a simple custom plug, but it would make more sense integrated into the instrumentation and have it _just work_ :tm: 

**Additional context**
This is very useful if you are running an application in a kubernetes cluster and have a proxy layer between applications, or running a micro service architecture.

**Comment by tsloughter** [comment]
I don't think this is in the spec yet so likely will have to stay in application code.

Since you mention use in microservices, I take it this is different from the use in returning to javascript client end code in the browser? I know that has a spec in the process as part of W3C tracecontext, unsure about general purpose response header.

**Comment by tsloughter** [comment]
I see W3C appears to already have this header so maybe it is something that can be included in Otel spec soon https://github.com/w3c/trace-context/blob/main/spec/21-http_response_header_format.md

Can you describe how you would use this? Trying to understand if this is a case where a new span id is actually needed for the response.

**Comment by btkostner** [comment]
Sorry for the late reply.

In our context, we run an elixir application in a kubernetes cluster with istio as a proxy. Istio can include an egress trace for things exiting the cluster. From what I gather, this should be the same as returning to javascript client end code.

**Comment by tsloughter** [comment]
Yes, this would be a good optional Plug (I think?) to add a response header from the current context.

**Comment by btkostner** [comment]
I'll do it in the application side of things. I didn't realize there was an API for injecting and extracting trace context already when I opened this issue (I do now). Thanks for the help!
